spring:
  application:
    name: demo
  datasource:
      url: lizard.c6de8wseq94u.us-east-1.rds.amazonaws.com/mysql
      username: tomthelizard
      password: lizarddd
      driver-class-name: com.mysql.cj.jdbc.Driver
